### ISSUE TITLE
Implement an MVP with an always-agree interaction and automatic consent

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-dummy#1]
This wallet is for testing and development purpose. It exposes capabilities to script the responses, and tamper with the regular workflow of the wallet. This is needed to easily test error and edge cases.

By default, it will accept every request issued. As a result, **this implementation is insecure by design. It should not be used for production.**

#### CLI
Expose only the necessary command to have a wallet up and running:
- [ ] `service run`

#### Service
- [ ] The service should accept all request by default
- [ ] The service should be able to talk to real nodes
- [ ] Support flags to specify which wallet will be is use
- [ ] Support automatic consent for API v1

#### Technical details
- [ ] Log every choices on the output as JSON

**Comment by radoslaw-szpiech** [comment]
It should allow 
- importing network,
- choosing network in CLI,
- creating public keys,
- CLI flags and arguments `--automatic-consent`, `--wallet-name`, `--passphrase`

**Comment by ValentinTrinque** [comment]
I've been taking a step back, I think we should use the original vegawallet CLI as much as possible instead of re-implementing the same features. So only the specific command lines to start the service will be implemented by the dummy wallet.
